/*
 * TransferZero API
 * Reference documentation for the TransferZero API V1
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.transferzero.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The type of the identity card used by the sender or recipient:  - &#x60;PP&#x60;: Passport - &#x60;ID&#x60;: National Identity Card - &#x60;O&#x60;: Other type of identity card - &#x60;DL&#x60;: Driving License - &#x60;OT&#x60;: Other type of identity card - &#x60;DNI&#x60;: Documento Nacional de Identidad (Peru) - &#x60;RUC&#x60;: Registro Único de Contribuyentes (Peru, business) - &#x60;CE&#x60;: Carnet de Extranjería (Peru, foreign national) - &#x60;PASS&#x60;: Passport (Peru) - &#x60;CI&#x60;: Cédula de Identidad (Costa Rica, individual) - &#x60;CJ&#x60;: Cédula Jurídica (Costa Rica, business) - &#x60;CR&#x60;: Cédula de Residencia (Costa Rica, resident)
 */
@JsonAdapter(PayoutMethodIdentityCardTypeEnum.Adapter.class)
public enum PayoutMethodIdentityCardTypeEnum {
  
  O("O"),
  
  PP("PP"),
  
  ID("ID"),
  
  DL("DL"),
  
  OT("OT"),
  
  DNI("DNI"),
  
  RUC("RUC"),
  
  CE("CE"),
  
  PASS("PASS"),
  
  CI("CI"),
  
  CJ("CJ"),
  
  CR("CR");

  private String value;

  PayoutMethodIdentityCardTypeEnum(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static PayoutMethodIdentityCardTypeEnum fromValue(String value) {
    for (PayoutMethodIdentityCardTypeEnum b : PayoutMethodIdentityCardTypeEnum.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<PayoutMethodIdentityCardTypeEnum> {
    @Override
    public void write(final JsonWriter jsonWriter, final PayoutMethodIdentityCardTypeEnum enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public PayoutMethodIdentityCardTypeEnum read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return PayoutMethodIdentityCardTypeEnum.fromValue(value);
    }
  }
}

