/*
 * TransferZero API
 * Reference documentation for the TransferZero API V1
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.transferzero.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.UUID;
import org.joda.time.DateTime;

/**
 * PoliticallyExposedPerson
 */

public class PoliticallyExposedPerson {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Integer id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_POSITION = "position";
  @SerializedName(SERIALIZED_NAME_POSITION)
  private String position;

  public static final String SERIALIZED_NAME_STARTED_DATE = "started_date";
  @SerializedName(SERIALIZED_NAME_STARTED_DATE)
  private DateTime startedDate;

  public static final String SERIALIZED_NAME_ENDED_DATE = "ended_date";
  @SerializedName(SERIALIZED_NAME_ENDED_DATE)
  private DateTime endedDate;

  public static final String SERIALIZED_NAME_SENDER_ID = "sender_id";
  @SerializedName(SERIALIZED_NAME_SENDER_ID)
  private UUID senderId;

  public static final String SERIALIZED_NAME_CREATED_AT = "created_at";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private DateTime createdAt;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updated_at";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  private DateTime updatedAt;


   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "")

  public Integer getId() {
    return id;
  }




  public PoliticallyExposedPerson name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Full name of the politically exposed person 
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Ronald Reagan", value = "Full name of the politically exposed person ")

  public String getName() {
    return name;
  }



  public void setName(String name) {
    this.name = name;
  }


  public PoliticallyExposedPerson position(String position) {
    
    this.position = position;
    return this;
  }

   /**
   * The office held by the politically exposed person 
   * @return position
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "President of the United States", value = "The office held by the politically exposed person ")

  public String getPosition() {
    return position;
  }



  public void setPosition(String position) {
    this.position = position;
  }


  public PoliticallyExposedPerson startedDate(DateTime startedDate) {
    
    this.startedDate = startedDate;
    return this;
  }

   /**
   * The date on which the person started holding the office 
   * @return startedDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The date on which the person started holding the office ")

  public DateTime getStartedDate() {
    return startedDate;
  }



  public void setStartedDate(DateTime startedDate) {
    this.startedDate = startedDate;
  }


  public PoliticallyExposedPerson endedDate(DateTime endedDate) {
    
    this.endedDate = endedDate;
    return this;
  }

   /**
   * The date on which the person ended holding the office 
   * @return endedDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The date on which the person ended holding the office ")

  public DateTime getEndedDate() {
    return endedDate;
  }



  public void setEndedDate(DateTime endedDate) {
    this.endedDate = endedDate;
  }


  public PoliticallyExposedPerson senderId(UUID senderId) {
    
    this.senderId = senderId;
    return this;
  }

   /**
   * The ID of the Sender to whom the person is attached to 
   * @return senderId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "83a4f5fd-9260-4aaa-9743-63f8a6d8309d", value = "The ID of the Sender to whom the person is attached to ")

  public UUID getSenderId() {
    return senderId;
  }



  public void setSenderId(UUID senderId) {
    this.senderId = senderId;
  }


   /**
   * Date and time the person was created
   * @return createdAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Date and time the person was created")

  public DateTime getCreatedAt() {
    return createdAt;
  }




   /**
   * Date and time the person was updated
   * @return updatedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Date and time the person was updated")

  public DateTime getUpdatedAt() {
    return updatedAt;
  }




  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PoliticallyExposedPerson politicallyExposedPerson = (PoliticallyExposedPerson) o;
    return Objects.equals(this.id, politicallyExposedPerson.id) &&
        Objects.equals(this.name, politicallyExposedPerson.name) &&
        Objects.equals(this.position, politicallyExposedPerson.position) &&
        Objects.equals(this.startedDate, politicallyExposedPerson.startedDate) &&
        Objects.equals(this.endedDate, politicallyExposedPerson.endedDate) &&
        Objects.equals(this.senderId, politicallyExposedPerson.senderId) &&
        Objects.equals(this.createdAt, politicallyExposedPerson.createdAt) &&
        Objects.equals(this.updatedAt, politicallyExposedPerson.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, position, startedDate, endedDate, senderId, createdAt, updatedAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PoliticallyExposedPerson {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    position: ").append(toIndentedString(position)).append("\n");
    sb.append("    startedDate: ").append(toIndentedString(startedDate)).append("\n");
    sb.append("    endedDate: ").append(toIndentedString(endedDate)).append("\n");
    sb.append("    senderId: ").append(toIndentedString(senderId)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

