name: Publish Package to Maven
on:
  push:
    branches:
      - BTA-11168-ci-cd-action
      - master
  workflow_dispatch:

jobs:
  release-transferzero-javascript-sdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          server-id: ossrh
          server-username: ${{ secrets.MAVEN_USERNAME }}
          server-password: ${{ secrets.MAVEN_PASSWORD }}
  
      - name: Publish Maven package
        run: mvn --batch-mode deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}

      # - name: Tag the release
      #   run: |
      #     NEXT_TAG=$(awk -F'"' '/"version": ".+"/{ print $4; exit; }' package.json)
      #     git tag $NEXT_TAG
      #     git push --tags
